### PR TITLE
Itemsdisplaypage#9

### PR DESCRIPTION
**Pull request by Maarimar**

### CODE REVIEW

**Comment by Maarimar** [comment]
I merged all the commits into this branch. Not sure how to di it into the original branch.

**Comment by royemosby** [comment]
> I merged all the commits into this branch. Not sure how to do it into the original branch.

The other work has to be moved into the original working branch. When you push the commits, it'll automatically update the PR that was already in place.

**Comment by Maarimar** [comment]
I did git merge itemCardComponent into Itemsdisplaypage#9 but what it did was create a new branch with the same name. I was in Itemsdisplaypage#9 at the time so not sure why it did that

**Comment by royemosby** [comment]
That's because it's not the same branch - you're using a hash where the original branch was using a dash. I'll go ahead and close the other one out and we'll stick with this one.

**Comment by royemosby** [comment]
Hi @Maarimar I am going to add "Draft" to the title just to make a not this PR is not ready yet. When you get a chance to make the card changes, just adjust the title back + ping me on Slack.

**Comment by royemosby** [comment]
Work added through [PR20](https://github.com/Code-the-Dream-School/ffprac-team7-front/pull/20) and closing this PR.

**Pull request closed without merging**
